In [38]:
import pandas as pd

df = pd.read_excel('C:/대학수업/2022.1학기/스프레드시트/중간데이터/restaurant.xlsx')
df.head(3)

         업소명                                 소재지  유형 주요메뉴
0  전주콩나물한우국밥  경기도 부천시 심곡본동 590-6번지 그린화인빌 1층 105호  한식   국밥
1      숲속의라움             경기도 부천시 송내동 449-16번지 1층  양식  파스타
2     엉터리생고기        경기도 부천시 심곡본동 679-14번지 , 1~2층  한식  삼겹살

In [39]:
temp = pd.DataFrame()
temp['시'] = df['소재지'].str.split(expand=True)[1]
temp['동'] = df['소재지'].str.split(expand=True)[2]
temp

      시     동
0   부천시  심곡본동
1   부천시   송내동
2   부천시  심곡본동
3   부천시   송내동
4   부천시   송내동
..  ...   ...
68  부천시    상동
69  부천시    상동
70  부천시    상동
71  부천시    중동
72  부천시    상동

[73 rows x 2 columns]

In [40]:
df.drop('소재지',axis=1,inplace=True)
data = pd.concat([df,temp],axis=1)
data

            업소명  유형 주요메뉴    시     동
0     전주콩나물한우국밥  한식   국밥  부천시  심곡본동
1         숲속의라움  양식  파스타  부천시   송내동
2        엉터리생고기  한식  삼겹살  부천시  심곡본동
3         털보해물탕  한식  해물탕  부천시   송내동
4   조마루감자탕중동남부점  한식  감자탕  부천시   송내동
..          ...  ..  ...  ...   ...
68    청정바지락생칼국수  한식  칼국수  부천시    상동
69         화로구이  한식   갈비  부천시    상동
70    털랭이매운탕고향집  한식  매운탕  부천시    상동
71        개성손만두  한식   만두  부천시    중동
72      강원토종삼계탕  한식  삼계탕  부천시    상동

[73 rows x 5 columns]

In [41]:
new_data=data.groupby(by='유형')
new_data1 = new_data.get_group('뷔페')
new_data1

               업소명  유형  주요메뉴    시     동
20        드마리스 부천점  뷔페    뷔페  부천시    상동
23            라비에벨  뷔페    뷔페  부천시    상동
24           에스컨벤션  뷔페    뷔페  부천시    상동
35        엠제이타워컨벤션  뷔페    뷔페  부천시  소사본동
55        중경홍중샤브뷔페  뷔페  샤브샤브  부천시   심곡동
58  채림웨딩부페．라시떼 데장땅  뷔페    뷔페  부천시   심곡동

In [44]:
df = data.query('동 =="송내동" and 주요메뉴=="파스타"')
df

     업소명  유형 주요메뉴    시    동
1  숲속의라움  양식  파스타  부천시  송내동